### ISSUE TITLE
Micropatch 0.9.15.1.1 bug on minimap

### ISSUE THREAD

**Issue by Kucus77** [VasyaPRO/StatsInBattle#3]
![shot_200](https://cloud.githubusercontent.com/assets/20968043/17585569/da93de90-5fbc-11e6-9dcf-64a5f0bafbef.jpg)
![shot_201](https://cloud.githubusercontent.com/assets/20968043/17585579/f85a3866-5fbc-11e6-86e9-b5378dddbc11.jpg)
Hi,
after todays micropatch of WoT to 0.9.15.1.1 there is some bug on minimap. direction of look is reversed.
Look at screenshot, Shot_200 is without this mod, Shot 201 is with this mod.

**Comment by VasyaPRO** [comment]
On version 2.1.1 the same?

**Comment by Kucus77** [comment]
I am downloading now, will report.

**Comment by Kucus77** [comment]
OK, on version 2.1.1 it is working well. 
No problém.
Thank you very much for your great work.
